from typing import Any, Dict, Protocol


class IMetricsManager(Protocol):
    def record_flush(self, duration_ms: float, success: bool) -> None: ...
    def increment(self, metric: str) -> None: ...
    def get_metrics(self) -> Dict[str, Any]: ...
